### ISSUE TITLE
Module no longer working

### ISSUE THREAD

**Issue by D1SoveR** [Magisk-Modules-Repo/Fdroid-Priv#4]
After an update to the latest version (following @ryaniskira change to his Device Owner fork), F-Droid no longer recognises the extension and doesn't use it for package management.
I wasn't able to get it working by enabling the admin access for the package, or putting the `device_owner.xml` file in manually, and setting device owner using `dpm` fails if the device has any accounts set up.

Can the method to make the module work be documented in readme, or failing that, can the change be reverted?

**Comment by RyanHakurei** [comment]
I can revert the PR real quick.

**Comment by RyanHakurei** [comment]
Module should be functional again.

**Comment by D1SoveR** [comment]
Can confirm, reinstalling the module after the revert, the extension is functional and recognised by F-Droid client again.
