### ISSUE TITLE
Module won't auto update. Keeping both module version installed will cause conflict.

### ISSUE THREAD

**Issue by kulmegil** [Magisk-Modules-Repo/Fdroid-Priv#5]
Magisk won't offer users auto update from previous version, Manual action is now required.

It is also possible for user to keep both installed. This will result in conflicting behavior as both try to inject into system priviliged extension apk - with same package name but different versions. In my test it was the apk from older version that replaced the newer one.

This is the result of module id been changed (Fdroid-Priv → Fdroid-Classic-Priv).
This is aside from bug #4

**Comment by RyanHakurei** [comment]
I reverted that PR for now to look into why that F-Droid would not recognize that fork and use it.
