### ISSUE TITLE
Magisk 22 compatibility

### ISSUE THREAD

**Issue by vasyugan** [Magisk-Modules-Repo/Fdroid-Priv#8]
Trying to install the module on Magisk v22 fails, it says it requires version 20.

**Comment by strugee** [comment]
I cannot reproduce on a Pixel 3a XL running stock Android 11 RQ2A.210405.005 + Magisk 22.1.

**Comment by vasyugan** [comment]
> 
> 
> I cannot reproduce on a Pixel 3a XL running stock Android 11 RQ2A.210405.005 + Magisk 22.1.

There seems to be a deeper issue here. Each time I launch Magisk Manager says "Zusätzliche Einrichtung erforderlich" (= "additional installation required"). When I click "yes" it  wants to download a zip, goes into reboot and does something, which apparently doesn't fix things. (It doesn't boot into TWRP, but into the system). That's the case since I upgraded to LineageOS 18.

After trying a number of times, this seems to have fixed itself and now the F-Droid module works as it should.
